// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkRLdu5o5hwOswStf9nMODozKrb-7_vrI',
    appId: '1:463530012666:web:fbc410ee6a99f5f567fe43',
    messagingSenderId: '463530012666',
    projectId: 'job-scraper-9ccef',
    authDomain: 'job-scraper-9ccef.firebaseapp.com',
    storageBucket: 'job-scraper-9ccef.firebasestorage.app',
    measurementId: 'G-TG1SR1KXJZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY7ugbGzpfQrn9nHe1tAq-J4nhFxT_uX8',
    appId: '1:463530012666:android:dcb9161a8246a93c67fe43',
    messagingSenderId: '463530012666',
    projectId: 'job-scraper-9ccef',
    storageBucket: 'job-scraper-9ccef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6w2YBbY4M87DfBmEFqiUVL251aUqICVk',
    appId: '1:463530012666:ios:6a75401cb94962d567fe43',
    messagingSenderId: '463530012666',
    projectId: 'job-scraper-9ccef',
    storageBucket: 'job-scraper-9ccef.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6w2YBbY4M87DfBmEFqiUVL251aUqICVk',
    appId: '1:463530012666:ios:6a75401cb94962d567fe43',
    messagingSenderId: '463530012666',
    projectId: 'job-scraper-9ccef',
    storageBucket: 'job-scraper-9ccef.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkRLdu5o5hwOswStf9nMODozKrb-7_vrI',
    appId: '1:463530012666:web:1b530f7f16bf758d67fe43',
    messagingSenderId: '463530012666',
    projectId: 'job-scraper-9ccef',
    authDomain: 'job-scraper-9ccef.firebaseapp.com',
    storageBucket: 'job-scraper-9ccef.firebasestorage.app',
    measurementId: 'G-DBVMZK4RHH',
  );
}
